spring.application.name=gathera

spring.web.error.include-message=always
spring.datasource.url=jdbc:postgresql://localhost:5440/postgres
spring.datasource.username=postgres
spring.datasource.password=new_root_1689_pass

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/changelog-master.yaml
logging.level.org.springframework.boot.autoconfigure.liquibase=DEBUG


logging.level.org.liquibase=DEBUG

jwt.lifetime=86400000
jwt.secret-key=d8a7e2c5f9b1e4d3f7a6b4c9d0e1k2a7n4c5d6e7f8a9b0c1d2e3f4a0k7n5v8e5g1
